### ISSUE TITLE
Children of inner scene is duplicated when instantiated

### ISSUE THREAD

**Issue by dadidudedon** [KoBeWi/Godot-Prefab#1]
I have Prefab setup like this
![Godot_v4 3-dev5_win64_NSHgNYG3ig](https://github.com/KoBeWi/Godot-Prefab/assets/68837424/5e6f7507-b623-4395-8739-2ffb76ac492a)
But when I instantiate this prefab it will be like
![Godot_v4 3-dev5_win64_uOfsBc0vR5](https://github.com/KoBeWi/Godot-Prefab/assets/68837424/34ccb017-d474-4ae1-b5fb-999481bfe397)
As you can see the children of Card is duplicated for some reason

**Comment by KoBeWi** [comment]
I can't reproduce it.
![image](https://github.com/KoBeWi/Godot-Prefab/assets/2223172/15d1a405-4d98-480f-b993-597a209d3ba6)
Any chance you could share some minimal setup that has this bug?

**Comment by dadidudedon** [comment]
[prefab_mrp.zip](https://github.com/KoBeWi/Godot-Prefab/files/15047374/prefab_mrp.zip)
here
Looks like it only happens on control node with certain setup 

I'm using Godot 4.3 dev5 on windows

EDIT: It only happens when root is container node, I'm not familiar with how container works so Im not sure why this happens

**Comment by KoBeWi** [comment]
I don't get why it happens only under this specific node, but this commit should fix it: f26877aa3836aa067c8386ab68b46ab00b056314
Please test.

**Comment by dadidudedon** [comment]
It seems to be fixed, Thanks
